
namespace RT.Generexes
{
    /// <summary>Encapsulates preliminary information about matches generated by <see cref="Generex{T,TResult}"/>.</summary>
    /// <typeparam name="TResult">Type of objects generated from each match of the regular expression.</typeparam>
    /// <remarks>This type is an implementation detail. It is not intended to be used outside this library.
    /// However, it cannot be made internal because it is used as a generic type parameter in a base-type declaration.</remarks>
    public struct GenerexMatchInfo<TResult>
    {
        internal TResult Result { get; private set; }
        internal int Length { get; private set; }
        internal GenerexMatchInfo(TResult result, int length) : this() { Result = result; Length = length; }
        internal GenerexMatchInfo<TResult> Add(int extraLength)
        {
            return new GenerexMatchInfo<TResult>(Result, Length + extraLength);
        }
    }
}
